Reduce test logging
eclipse/transformer pull request #161
Opened 2021-08-17 02:50 UTC by tbitonti

Remove display of bytes for loaded classes and manifests.
Trimmed manifest test data and adjusted the related test counts.

2021-08-18 19:57 UTC, jimblye approved these changes

2021-09-09 14:37 UTC, bjhargrave requested changes
If we are going to remove something, lets remove it. Just commenting it out is confusing to future readers. We can always go back to this commit to resurrect removed code.

2021-09-14 17:35 UTC, tbitonti commented
> 
> 
> If we are going to remove something, lets remove it. Just commenting it out is confusing to future readers. We can always go back to this commit to resurrect removed code.

For these changes, I left the code in comments since it is logging which is useful while diagnosing test failures, and I'm looking to to re-enable this code with new logging option, still to be determined.

2021-09-17 19:09 UTC, bjhargrave approved these changes

2021-09-17 19:10 UTC, merged