Fixes #519 - Unable to run Eclipse Transformer on Java 21 using the Maven plugin
eclipse/transformer pull request #529
Opened 2023-12-27 16:40 UTC by mnriem

2023-12-28 13:24 UTC, bjhargrave requested changes
The correct artifactId is `bndlib`. See

https://github.com/eclipse/transformer/blob/50f259152cb5ae355074d676652834c6904790cb/maven-plugins/transformer-maven-plugin/pom.xml#L45-L48

2023-12-28 13:24 UTC, bjhargrave commented on maven-plugins/transformer-maven-plugin/README.md
> +If you are using Java 21 or later you will need to configure the Maven plugin to use a specific version of the `biz.aQute.bnd` dependency.
```suggestion
If you are using Java 21 or later you will need to configure the Maven plugin to use a specific version of the `biz.aQute.bndlib` dependency.
```

2023-12-28 13:24 UTC, bjhargrave commented on maven-plugins/transformer-maven-plugin/README.md
> +    <artifactId>biz.aQute.bnd</artifactId>
```suggestion
    <artifactId>biz.aQute.bndlib</artifactId>
```

2023-12-28 13:24 UTC, bjhargrave commented on maven-plugins/transformer-maven-plugin/README.md
> +E.g.
```suggestion
For example:
```

2023-12-31 15:16 UTC, mnriem commented
@bjhargrave Please review again. Changes have been applied.

2023-12-31 22:26 UTC, bjhargrave approved these changes

2024-01-01 12:20 UTC, merged